# docker-compose.yml

services:
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app_net
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  user_service:
    build: ./user_service
    container_name: user_service
    env_file:
      - .env
    networks:
      - app_net
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    depends_on:
      team_service:
        condition: service_started
      db:
        condition: service_healthy
      

  team_service:
    build: ./team_service
    container_name: team_service
    env_file:
      - .env
    networks:
      - app_net
    ports:
      - "${TEAM_SERVICE_PORT}:${TEAM_SERVICE_PORT}"
    depends_on:
      - db

  # org_structure_service:
  #   build: ./org_structure_service
  #   container_name: org_structure_service
  #   env_file:
  #     - .env
  #   networks:
  #     - app_net
  #   ports:
  #     - "${ORG_STRUCTURE_SERVICE_PORT}:${ORG_STRUCTURE_SERVICE_PORT}"
  #   depends_on:
  #     - db

  # tasks_service:
  #   build: ./tasks_service
  #   container_name: tasks_service
  #   env_file:
  #     - .env
  #   networks:
  #     - app_net
  #   ports:
  #     - "${TASKS_SERVICE_PORT}:${TASKS_SERVICE_PORT}"
  #   depends_on:
  #     - db

  # meetings_service:
  #   build: ./meetings_service
  #   container_name: meetings_service
  #   env_file:
  #     - .env
  #   networks:
  #     - app_net
  #   ports:
  #     - "${MEETINGS_SERVICE_PORT}:${MEETINGS_SERVICE_PORT}"
  #   depends_on:
  #     - db

  # calendar_service:
  #   build: ./calendar_service
  #   container_name: calendar_service
  #   env_file:
  #     - .env
  #   networks:
  #     - app_net
  #   ports:
  #     - "${CALENDAR_SERVICE_PORT}:${CALENDAR_SERVICE_PORT}"
  #   depends_on:
  #     - db

  # admin_service:
  #   build: ./admin_service
  #   container_name: admin_service
  #   env_file:
  #     - .env
  #   networks:
  #     - app_net
  #   ports:
  #     - "${ADMIN_SERVICE_PORT}:${ADMIN_SERVICE_PORT}"
  #   depends_on:
  #     - db

networks:
  app_net:
    driver: bridge

volumes:
  postgres_data:
